[workspace]

members = [
  "hello-world",
  "x-cubic",
  "rectangle",
  "even-or-odd",
  "watch",
  "sum-of-positive",
  "remove-first-and-last-character",
  "string-repeat",
  "small-large-equal",
  "reversed-strings",
  "summation",
  "smallest",
]